var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca="undefined"!=typeof document?document.currentScript?.src:void 0,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),m,p=!1,ha,ia,q,r,ja,ka,u,v,w,x,la;
function ma(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){if(!m)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==na&&m)a=new Uint8Array(m);else throw"both async and sync fetching of the wasm failed";return a}async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}
async function qa(a){var b=na;if(!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var sa=a=>{for(;0<a.length;)a.shift()(h)},ta=[],ua=[],va=()=>{var a=h.preRun.shift();ua.push(a)},y=0,z=null,wa=!0;
function xa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ja[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":la[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:ma(`invalid type for setValue: ${c}`)}}
var ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&ya)return ya.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},za=
a=>{if(!(a instanceof ra||"unwind"==a))throw a;},Aa=a=>{ha=a;wa||(h.onExit?.(a),p=!0);throw new ra(a);},Ba=a=>{ha=a;Aa(a)},Ca=()=>{if(!wa)try{var a=ha;ha=a;Aa(a)}catch(b){za(b)}};function Da(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Ea=!1,Fa=[];
function Ga(){function a(){Ea=document.pointerLockElement===h.canvas}if(!Ha){Ha=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ea&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ia(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,Te:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof Ja&&(e=Ka(a,g)))var l=C[e].je}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&La(e),Fa.forEach(n=>n()),Ga());return l}
var Ha,D=12288,Ma=!1,Na=0,Oa=0,Pa=0,E={alpha:!1,depth:!1,stencil:!1,antialias:!1},Qa={},Ra,F,Sa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Ta=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ua=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Va=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Wa=1,Xa=[],G=[],Ya=[],H=[],J=[],K=[],Za=[],C=[],M=[],$a={},ab=4,bb=0,cb=a=>{for(var b=Wa++,c=a.length;c<b;c++)a[c]=null;return b},db=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=F[c](),f=g&&cb(d);g?(g.name=f,d[f]=g):N||=1282;u[b+4*e>>2]=f}},Ka=(a,b)=>{a.Oe||(a.Oe=a.getContext,a.getContext=function(d,e){e=a.Oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?eb(c,b):0},eb=(a,b)=>{var c=
cb(C),d={handle:c,attributes:b,version:b.Te,je:a};a.canvas&&(a.canvas.ne=d);C[c]=d;("undefined"==typeof b.ef||b.ef)&&fb(d);return c},La=a=>{gb=C[a];h.ctx=F=gb?.je},fb=a=>{a||=gb;if(!a.kf){a.kf=!0;var b=a.je;b.Bf=b.getExtension("WEBGL_multi_draw");b.gf=b.getExtension("EXT_polygon_offset_clamp");b.ff=b.getExtension("EXT_clip_control");b.pf=b.getExtension("WEBGL_polygon_mode");Sa(b);Ta(b);Ua(b);b.ie=b.getExtension("EXT_disjoint_timer_query");Va(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Ja={},N,gb,hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},O=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|
f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Q=a=>{var b=hb(a)+1,c=P(b);c&&O(a,c,b);return c},xb=(a,b,c,d,e)=>{function g(){return f<ib?(Ca(),!1):!0}jb=a;kb=d;var f=ib;lb=!1;mb=function(){if(!p)if(0<nb.length){var l=nb.shift();l.xf(l.qf);if(ob){var n=ob,t=0==n%1?n-1:Math.floor(n);ob=l.tf?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=ob??0,t=pb.wf??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&
setTimeout(mb,0)}else if(g())if(qb=qb+1|0,1==rb&&1<sb&&0!=qb%sb)R();else{0==rb&&(tb=performance.now());a:if(!p){for(l of ub)if(!1===l())break a;if(!p)try{a(),Ca()}catch(B){za(B)}for(n of vb)n()}g()&&R()}};e||(0<b?wb(0,1E3/b):wb(1,1),R());if(c)throw"unwind";},lb=!1,R=null,ib=0,jb=null,kb=0,rb=0,sb=0,qb=0,nb=[],ub=[],vb=[],yb=0;
function zb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===yb)yb=b+1E3/60;else for(;b+2>=yb;)yb+=1E3/60;setTimeout(a,Math.max(yb-b,0))}}
var pb={},mb,ob,tb,Ab,wb=(a,b)=>{rb=a;sb=b;if(jb)if(lb||=!0,0==a)R=function(){setTimeout(mb,Math.max(0,tb+b-performance.now())|0)};else if(1==a)R=function(){zb(mb)};else if(2==a){if("undefined"==typeof Ab)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ab=d=>{c.push(d);postMessage("setimmediate","*")}}else Ab=setImmediate;R=function(){Ab(mb)}}},Bb=[],Cb=(a,b)=>{Bb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Bb.push(112==c?v[b>>2]:106==c?la[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Bb};function Db(a){var b=S.ee[a];b.target.removeEventListener(b.be,b.Re,b.ce);S.ee.splice(a,1)}function Eb(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of S.ke)if(e.Ie==a&&d(e.Pe,c))return;S.ke.push({Ie:a,Ve:b,Pe:c});S.ke.sort((g,f)=>g.Ve<f.Ve)}function Fb(a){S.ke=S.ke.filter(b=>b.Ie!=a)}
function Gb(){return navigator.userActivation?navigator.userActivation.isActive:S.De&&S.Ze.pe}function Hb(){if(Gb()){var a=S.ke;S.ke=[];for(var b of a)b.Ie(...b.Pe)}}function T(a){if(!a.target)return-4;if(a.de)a.Re=function(c){++S.De;S.Ze=a;Hb();a.fe(c);Hb();--S.De},a.target.addEventListener(a.be,a.Re,a.ce),S.ee.push(a);else for(var b=0;b<S.ee.length;++b)S.ee[b].target==a.target&&S.ee[b].be==a.be&&Db(b--);return 0}
function Ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={rf:0,Ce:0,Ee:0,xe:0,Ne:0,Ke:0,Ae:0,vf:0,Cf:0,uf:0,Be:0,Ge:0,Me:0,Je:0,zf(a,b,c){q.set(q.subarray(b,b+c),a)},Df(){for(;S.ee.length;)Db(S.ee.length-1);S.ke=[]},De:0,ke:[],ee:[],mf:(a,b)=>{for(var c=0;c<S.ee.length;++c)S.ee[c].target!=a||b&&b!=S.ee[c].be||Db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Jb=[0,document,window],U=a=>{a=2<a?a?A(r,a):"":a;return Jb[a]||document.querySelector(a)},Lb=a=>{var b=hb(a)+1,c=Kb(b);O(a,c,b);return c},Ob=a=>
{var b=Mb(),c=Kb(8),d=c+4;a=Lb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Nb(b);return c},Pb=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Qb=(a,b,c)=>{if(a.sf){var d=Mb();a=Lb(a.id);Pb(a,b,c);Nb(d)}else a.width=b,a.height=c},Rb={},Sb=[],Tb,V=a=>{var b=Sb[a];b||(Sb[a]=b=Tb.get(a));return b},Ub=a=>{function b(){Da()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Qb(a,d,e),a.style.width=g,a.style.height=
f,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=Wc,a.style.marginRight=Xc,a.style.marginTop=Yc,a.style.marginBottom=Zc,document.body.style.margin=$c,document.documentElement.style.overflow=ad,document.body.scroll=bd,a.style.le=cd,a.ne&&a.ne.je.viewport(0,0,d,e),Rb.qe&&V(Rb.qe)(37,0,Rb.Qe))}var c=Ob(a),d=c[0],e=c[1],g=a.style.width,
f=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,Wc=a.style.marginLeft,Xc=a.style.marginRight,Yc=a.style.marginTop,Zc=a.style.marginBottom,$c=document.body.style.margin,ad=document.documentElement.style.overflow,bd=document.body.scroll,cd=a.style.le;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Vb=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Wb=a=>0>Jb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Xb=(a,b)=>{if(0!=b.He||0!=b.ye){Ub(a);var c=b.nf?innerWidth:screen.width,d=b.nf?innerHeight:screen.height,e=Wb(a),g=e.width;e=e.height;var f=Ob(a),l=f[0];f=f[1];3==b.He?(Vb(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.He&&(c*f<l*d?(g=f*c/l,Vb(a,(d-g)/2,0),d=g):(g=l*d/f,Vb(a,0,(c-g)/2),c=g));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let t;(t=document.body.style).backgroundColor||
(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.hf&&(a.style.le="optimizeSpeed",a.style.le="-moz-crisp-edges",a.style.le="-o-crisp-edges",a.style.le="-webkit-optimize-contrast",a.style.le="optimize-contrast",a.style.le="crisp-edges",a.style.le="pixelated");n=2==b.ye?devicePixelRatio:1;0!=b.ye&&(c=c*n|0,d=d*n|0,Qb(a,c,d),a.ne&&a.ne.je.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Rb=b;b.qe&&V(b.qe)(37,0,b.Qe);return 0},Yb=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Zb=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;O(b.id,a+1112,64);O(b.mapping,a+1176,64)},$b=(a,b)=>{F.attachShader(G[a],K[b])},ac=(a,b)=>{F.bindBuffer(a,Xa[b])},bc=(a,b)=>F.blendFunc(a,b),cc=(a,b,c,d)=>{F.bufferData(a,c?r.subarray(c,c+b):b,d)},dc=a=>F.clear(a),ec=(a,b,c,d)=>F.clearColor(a,b,c,d),fc=a=>{F.compileShader(K[a])},gc=()=>{var a=cb(G),b=F.createProgram();b.name=a;b.we=b.ue=b.ve=0;b.Le=1;G[a]=b;return a},hc=a=>{var b=cb(K);K[b]=F.createShader(a);
return b},ic=a=>F.disable(a),jc=[],kc=(a,b,c,d)=>{F.drawElements(a,b,c,d)},lc=a=>F.enable(a),mc=a=>{F.enableVertexAttribArray(a)},nc=(a,b)=>{db(a,b,"createBuffer",Xa)},oc=(a,b,c,d,e,g,f,l)=>{b=G[b];if(a=F[a](b,c))d=l&&O(a.name,l,d),e&&(u[e>>2]=d),g&&(u[g>>2]=a.size),f&&(u[f>>2]=a.type)},pc=(a,b)=>F.getAttribLocation(G[a],b?A(r,b):""),qc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(N||=1280);return;case 36345:d=0;break;case 34466:var e=F.getParameter(34467);d=
e?e.length:0}if(void 0===d)switch(e=F.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":N||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:N||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;
case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:N||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else N||=1281},rc=(a,b,c)=>{if(c){a=F.ie.getQueryObjectEXT(M[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else N||=1281},sc=(a,b,c)=>{if(c){a=F.ie.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else N||=1281},tc=()=>{var a=Va(F);return a=a.concat(a.map(b=>"GL_"+b))},uc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),vc=a=>{var b=a.oe,c=a.Xe,d;if(!b){a.oe=b={};a.We={};var e=F.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=F.getActiveUniform(a,d);var f=g.name;g=g.size;var l=uc(f);l=0<l?f.slice(0,
l):f;var n=a.Le;a.Le+=g;c[l]=[g,n];for(f=0;f<g;++f)b[n]=f,a.We[n++]=l}}},wc=(a,b)=>{b=b?A(r,b):"";if(a=G[a]){vc(a);var c=a.oe,d=0,e=b,g=uc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Xe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||F.getUniformLocation(a,b)))return d}else N||=1281;return-1},W=a=>{var b=F.$e;if(b){var c=b.oe[a];"number"==typeof c&&(b.oe[a]=c=F.getUniformLocation(b,b.We[a]+(0<c?`[${c}]`:"")));return c}N||=1282},xc=(a,b,c,d)=>{if(c)if(a=G[a],vc(a),a=F.getUniform(a,W(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else N||=1281},yc=(a,b,c,d)=>{if(c)if(a=F.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+
4*b>>2]=Math.fround(a[b])}else N||=1281},zc=a=>{a=G[a];F.linkProgram(a);a.oe=0;a.Xe={}},Ac=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ka;b=d*((bb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+ab-1&-ab);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Bc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=v[c+4*g>>2])?A(r,f,d?v[d+4*g>>2]:void 0):"";e+=f}F.shaderSource(K[a],e)},Cc=(a,b)=>{F.uniform1f(W(a),b)},X=[],
Dc=[],Ec=(a,b,c,d)=>{F.uniform3f(W(a),b,c,d)},Fc=(a,b,c,d)=>{if(18>=b){var e=X[16*b],g=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(W(a),!!c,e)},Gc=a=>{a=G[a];F.useProgram(a);F.$e=a},Hc=(a,b,c,d,e,g)=>{F.vertexAttribPointer(a,
b,c,!!d,e,g)},Ic=(a,b,c,d)=>F.viewport(a,b,c,d),Jc=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Gb()?Xb(a,b):b.df?(Eb(Xb,1,[a,b]),1):-2:-3:-4},Kc=()=>{try{if(navigator.getGamepads)return(S.te=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Lc=(a,b)=>{var c={target:U(2),be:"beforeunload",de:b,fe:(d=event)=>{var e=V(b)(28,0,a);e&&=e?A(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},ce:!0};return T(c)},Mc=
(a,b,c,d,e,g)=>{S.Ae||(S.Ae=P(256));a={target:U(a),be:g,de:d,fe:(f=event)=>{var l=f.target.id?f.target.id:"",n=S.Ae;O(Ib(f.target),n+0,128);O(l,n+128,128);V(d)(e,n,b)&&f.preventDefault()},ce:c};return T(a)},Nc=(a,b,c,d,e)=>{S.Be||(S.Be=P(276));return T({target:a,be:e,de:d,fe:(g=event)=>{var f=S.Be,l=Da(),n=!!l;q[f]=n;q[f+1]=S.fullscreenEnabled();var t=n?l:S.lf,B=t?.id||"";O(Ib(t),f+2,128);O(B,f+130,128);u[f+260>>2]=t?t.clientWidth:0;u[f+264>>2]=t?t.clientHeight:0;u[f+268>>2]=screen.width;u[f+272>>
2]=screen.height;n&&(S.lf=l);V(d)(19,f,b)&&g.preventDefault()},ce:c})},Oc=(a,b,c,d,e)=>{S.Ce||(S.Ce=P(1240));b={target:U(2),pe:!0,be:e,de:c,fe:(g=event)=>{var f=S.Ce;Zb(f,g.gamepad);V(c)(d,f,a)&&g.preventDefault()},ce:b};return T(b)},Pc=(a,b,c,d,e,g)=>{S.Ee||(S.Ee=P(160));a={target:U(a),be:g,de:d,fe:f=>{var l=S.Ee;x[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;q[l+12]=f.ctrlKey;q[l+13]=f.shiftKey;q[l+14]=f.altKey;q[l+15]=f.metaKey;q[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;
O(f.key||"",l+32,32);O(f.code||"",l+64,32);O(f.char||"",l+96,32);O(f.locale||"",l+128,32);V(d)(e,l,b)&&f.preventDefault()},ce:c};return T(a)},Qc=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ja[2*d+14]=b.button;ja[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=Wb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Rc=(a,b,c,d,e,g)=>{S.xe||(S.xe=
P(64));a=U(a);return T({target:a,pe:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,be:g,de:d,fe:(f=event)=>{Qc(S.xe,f,a);V(d)(e,S.xe,b)&&f.preventDefault()},ce:c})},Sc=(a,b,c,d)=>{S.Ge||(S.Ge=P(257));return T({target:a,be:"pointerlockchange",de:d,fe:(e=event)=>{var g=S.Ge,f=document.pointerLockElement;q[g]=!!f;var l=f?.id||"";O(Ib(f),g+1,128);O(l,g+129,128);V(d)(20,g,b)&&e.preventDefault()},ce:c})},Tc=(a,b,c,d)=>{S.Ke||(S.Ke=P(36));a=U(a);return T({target:a,be:"resize",de:d,fe:(e=event)=>{if(e.target==
a){var g=document.body;if(g){var f=S.Ke;u[f>>2]=0;u[f+4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;V(d)(10,f,b)&&e.preventDefault()}}},ce:c})},Uc=(a,b,c,d,e,g)=>{S.Je||(S.Je=P(1552));a=U(a);return T({target:a,pe:"touchstart"==g||"touchend"==g,be:g,de:d,fe:f=>{var l={},n=f.touches;for(var t of n)t.Se=t.Ue=0,l[t.identifier]=t;for(var B of f.changedTouches)B.Se=
1,l[B.identifier]=B;for(var L of f.targetTouches)l[L.identifier].Ue=1;n=S.Je;x[n>>3]=f.timeStamp;q[n+12]=f.ctrlKey;q[n+13]=f.shiftKey;q[n+14]=f.altKey;q[n+15]=f.metaKey;t=n+16;B=Wb(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Se,q[t+29]=I.Ue,u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++L)break;u[n+8>>2]=L;V(d)(e,n,b)&&f.preventDefault()},ce:c})},Vc=(a,
b,c)=>{var d=Jb[1];S.Me||(S.Me=P(8));return T({target:d,be:"visibilitychange",de:c,fe:(e=event)=>{var g=S.Me,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[g]=document.hidden;u[g+4>>2]=f;V(c)(21,g,a)&&e.preventDefault()},ce:b})},dd=(a,b,c,d)=>{S.Ne||(S.Ne=P(96));return T({target:a,pe:!0,be:"wheel",de:d,fe:(e=event)=>{var g=S.Ne;Qc(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;u[g+88>>2]=e.deltaMode;V(d)(9,g,b)&&e.preventDefault()},ce:c})},ed=
{},gd=()=>{if(!fd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in ed)void 0===ed[b]?delete a[b]:a[b]=ed[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);fd=c}return fd},fd,hd=[null,[],[]],jd=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d?.addEventListener(c,()=>{"suspended"===
a.state&&a.resume()},{once:!0})})})},kd=(a,b=[])=>{V(a)(...b)};h.requestAnimationFrame=zb;h.pauseMainLoop=function(){R=null;ib++};h.resumeMainLoop=function(){ib++;var a=rb,b=sb,c=jb;jb=null;xb(c,0,!1,kb,!0);wb(a,b);R()};h.preMainLoop&&ub.push(h.preMainLoop);h.postMainLoop&&vb.push(h.postMainLoop);for(let a=0;32>a;++a)jc.push(Array(a));for(var ld=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=ld.subarray(0,Y);var md=new Int32Array(288);for(Y=0;288>=Y;++Y)Dc[Y]=md.subarray(0,Y);h.noExitRuntime&&(wa=h.noExitRuntime);
h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.createContext=Ia;
var nd={1365844:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1365991:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1366225:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ae||("undefined"!==typeof AudioContext?b.ae=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ae=new webkitAudioContext),b.ae&&
"undefined"===typeof navigator.userActivation&&jd(b.ae));return void 0===b.ae?-1:0},1366777:()=>h.SDL2.ae.sampleRate,1366845:(a,b,c,d)=>{function e(){}function g(l){void 0!==f.capture.he&&(clearInterval(f.capture.he),f.capture.he=void 0,f.capture.me=void 0);f.capture.Fe=f.ae.createMediaStreamSource(l);f.capture.ge=f.ae.createScriptProcessor(b,a,1);f.capture.ge.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.ze=n.inputBuffer,kd(c,[d]))};
f.capture.Fe.connect(f.capture.ge);f.capture.ge.connect(f.ae.destination);f.capture.stream=l}var f=h.SDL2;f.capture.me=f.ae.createBuffer(a,b,f.ae.sampleRate);f.capture.me.getChannelData(0).fill(0);f.capture.he=setInterval(function(){f.capture.ze=f.capture.me;kd(c,[d])},b/f.ae.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},g,e)},1368538:(a,b,c,d)=>{var e=h.SDL2;e.audio.ge=e.ae.createScriptProcessor(b,0,a);e.audio.ge.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.he&&(clearInterval(e.audio.he),e.audio.he=void 0,e.audio.me=void 0),e.audio.se=g.outputBuffer,kd(c,[d]))};e.audio.ge.connect(e.ae.destination);"suspended"===e.ae.state&&(e.audio.me=e.ae.createBuffer(a,b,e.ae.sampleRate),e.audio.me.getChannelData(0).fill(0),e.audio.he=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.ae.resume();e.audio.se=e.audio.me;kd(c,[d]);e.audio.se=void 0},b/e.ae.sampleRate*1E3))},1369713:(a,b)=>{for(var c=h.SDL2,d=c.capture.ze.numberOfChannels,e=0;e<d;++e){var g=c.capture.ze.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)xa(a+4*f,g[f]);else for(f=0;f<b;++f)xa(a+4*(f*d+e),g[f])}},1370318:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.se.numberOfChannels,e=0;e<d;++e){var g=c.audio.se.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=w[a+(f*d+e)]}},1370807:a=>{var b=h.SDL2;if(a){void 0!==b.capture.he&&clearInterval(b.capture.he);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.ge&&(b.capture.ge.onaudioprocess=
function(){},b.capture.ge.disconnect());void 0!==b.capture.Fe&&b.capture.Fe.disconnect();b.capture=void 0}else void 0!=b.audio.ge&&b.audio.ge.disconnect(),void 0!==b.audio.he&&clearInterval(b.audio.he),b.audio=void 0;void 0!==b.ae&&void 0===b.audio&&void 0===b.capture&&(b.ae.close(),b.ae=void 0)},1371813:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Ye!==h.canvas&&(d.re=Ia(h.canvas,!1,!0),d.Ye=h.canvas);if(d.w!==a||d.h!==b||d.jf!==d.re)d.image=d.re.createImageData(a,b),d.w=a,d.h=b,d.jf=d.re;a=d.image.data;
b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=u[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.bf!==a&&(d.af=new Int32Array(a.buffer),d.cf=new Uint8Array(a.buffer),d.bf=a),a=d.af,c=a.length,a.set(u.subarray(b,b+c)),a=d.cf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=
255,b=b+4|0;d.re.putImageData(d.image,0,0)},1373279:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":
"url("+g.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);O(c,d,c.length+1);return d},1374267:a=>{h.canvas&&(h.canvas.style.cursor=a?A(r,a):"")},1374350:()=>{h.canvas&&(h.canvas.style.cursor="none")},1374419:()=>window.innerWidth,1374449:()=>window.innerHeight},od,P,Nb,Kb,Mb,pd={X:function(){return 0},Xa:function(){return 0},Ya:function(){},Ra:()=>{},Ga:a=>{if(12448==a)return D=12288,1;D=12300;return 0},Ja:(a,b,c,d,e)=>{if(62E3!=a)D=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)E.alpha=0<u[b+
4>>2];else if(12325==a)E.depth=0<u[b+4>>2];else if(12326==a)E.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],E.antialias=0<a;else if(12338==a)a=u[b+4>>2],E.antialias=1==a;else if(12544==a)E.yf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),D=12288,c=1):(D=12300,c=0)}return c},xa:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return D=12292,0;d+=8}if(2!=a)return D=12293,0;E.Te=a-1;E.Af=
0;Ra=Ka(h.canvas,E);if(0!=Ra)return D=12288,La(Ra),Fa.forEach(e=>e()),La(null),62004;D=12297;return 0},za:(a,b)=>{if(62E3!=a)return D=12296,0;if(62002!=b)return D=12293,0;D=12288;return 62006},ya:(a,b)=>{if(62E3!=a)return D=12296,0;if(62004!=b)return D=12294,0;a=Ra;gb===C[a]&&(gb=null);"object"==typeof S&&S.mf(C[a].je.canvas);C[a]?.je.canvas&&(C[a].je.canvas.ne=void 0);C[a]=null;D=12288;Na==b&&(Na=0);return 1},Aa:(a,b)=>{if(62E3!=a)return D=12296,0;if(62006!=b)return D=12301,1;Oa==b&&(Oa=0);Pa==b&&
(Pa=0);D=12288;return 1},Ka:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(62002!=b)return D=12293,0;if(!d)return D=12300,0;D=12288;switch(c){case 12320:return u[d>>2]=E.alpha?32:24,1;case 12321:return u[d>>2]=E.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=E.depth?24:0,1;case 12326:return u[d>>2]=E.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>
2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=E.antialias?4:0,1;case 12338:return u[d>>2]=E.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>
2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return D=12292,0}},P:a=>{D=12288;return 0!=a&&1!=a?0:62E3},wa:()=>D,Ha:(a,b,c)=>{if(62E3!=a)return D=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Ma=!0;D=12288;return 1},Ba:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(0!=d&&62004!=d)return D=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return D=12301,0;La(d?Ra:null);Na=d;Pa=b;Oa=c;D=12288;return 1},va:(a,b)=>{if(62E3!=a)return D=12296,0;D=12288;if(Qa[b])return Qa[b];
switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return D=12300,0}return Qa[b]=a},Ca:()=>{if(Ma)if(F)if(F.isContextLost())D=12302;else return D=12288,1;else D=12290;else D=12289;return 0},Da:(a,b)=>{if(62E3!=a)return D=12296,0;0==b?wb(0,0):wb(1,b);D=12288;return 1},Ia:a=>{if(62E3!=a)return D=12296,0;Pa=Oa=Na=0;Ma=!1;D=12288;return 1},Fa:()=>{D=12288;return 1},Ea:()=>{D=12288;return 1},Ma:(a,b,
c)=>{b=Cb(b,c);return nd[a](...b)},k:(a,b,c)=>{b=Cb(b,c);return nd[a](...b)},ta:(a,b,c)=>{b=Cb(b,c);return nd[a](...b)},Za:()=>Date.now(),pa:()=>{if(!S.fullscreenEnabled())return-1;Fb(Xb);var a=Jb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},sa:()=>{Fb(Yb);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},p:()=>devicePixelRatio,m:(a,b,c)=>{a=U(a);if(!a)return-4;
a=Wb(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},S:(a,b)=>{if(0>a||a>=S.te.length)return-5;if(!S.te[a])return-7;Zb(b,S.te[a]);return 0},U:()=>performance.now(),La:()=>S.te.length,ua:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Pd:a=>F.activeTexture(a),Od:$b,la:(a,b)=>{F.ie.beginQueryEXT(a,M[b])},Nd:(a,b,c)=>{F.bindAttribLocation(G[a],b,c?A(r,c):"")},Md:ac,Ld:(a,b)=>{F.bindFramebuffer(a,Ya[b])},Kd:(a,b)=>{F.bindRenderbuffer(a,H[b])},Jd:(a,b)=>{F.bindTexture(a,J[b])},da:a=>{F.bindVertexArray(Za[a])},
Id:(a,b,c,d)=>F.blendColor(a,b,c,d),Hd:a=>F.blendEquation(a),Gd:(a,b)=>F.blendEquationSeparate(a,b),Fd:bc,Ed:(a,b,c,d)=>F.blendFuncSeparate(a,b,c,d),Dd:cc,Cd:(a,b,c,d)=>{F.bufferSubData(a,b,r.subarray(d,d+c))},Bd:a=>F.checkFramebufferStatus(a),Ad:dc,yd:ec,xd:a=>F.clearDepth(a),wd:a=>F.clearStencil(a),$a:(a,b)=>{F.ff.clipControlEXT(a,b)},vd:(a,b,c,d)=>{F.colorMask(!!a,!!b,!!c,!!d)},ud:fc,td:(a,b,c,d,e,g,f,l)=>{F.compressedTexImage2D(a,b,c,d,e,g,r.subarray(l,l+f))},sd:(a,b,c,d,e,g,f,l,n)=>{F.compressedTexSubImage2D(a,
b,c,d,e,g,f,r.subarray(n,n+l))},rd:(a,b,c,d,e,g,f,l)=>F.copyTexImage2D(a,b,c,d,e,g,f,l),qd:(a,b,c,d,e,g,f,l)=>F.copyTexSubImage2D(a,b,c,d,e,g,f,l),pd:gc,od:hc,nd:a=>F.cullFace(a),md:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Xa[d];e&&(F.deleteBuffer(e),e.name=0,Xa[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Ya[d];e&&(F.deleteFramebuffer(e),e.name=0,Ya[d]=null)}},kd:a=>{if(a){var b=G[a];b?(F.deleteProgram(b),b.name=0,G[a]=null):N||=1281}},na:(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=M[d];e&&(F.ie.deleteQueryEXT(e),M[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(F.deleteRenderbuffer(e),e.name=0,H[d]=null)}},id:a=>{if(a){var b=K[a];b?(F.deleteShader(b),K[a]=null):N||=1281}},hd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(F.deleteTexture(e),e.name=0,J[d]=null)}},ca:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];F.deleteVertexArray(Za[d]);Za[d]=null}},gd:a=>F.depthFunc(a),fd:a=>{F.depthMask(!!a)},dd:(a,b)=>F.depthRange(a,b),cd:(a,
b)=>{F.detachShader(G[a],K[b])},bd:ic,ad:a=>{F.disableVertexAttribArray(a)},$c:(a,b,c)=>{F.drawArrays(a,b,c)},Sd:(a,b,c,d)=>{F.drawArraysInstanced(a,b,c,d)},Td:(a,b)=>{for(var c=jc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];F.drawBuffers(c)},_c:kc,Rd:(a,b,c,d,e)=>{F.drawElementsInstanced(a,b,c,d,e)},Zc:lc,Yc:mc,ka:a=>{F.ie.endQueryEXT(a)},Xc:()=>F.finish(),Wc:()=>F.flush(),Vc:(a,b,c,d)=>{F.framebufferRenderbuffer(a,b,c,H[d])},Uc:(a,b,c,d,e)=>{F.framebufferTexture2D(a,b,c,J[d],e)},Tc:a=>F.frontFace(a),Sc:nc,
Qc:(a,b)=>{db(a,b,"createFramebuffer",Ya)},oa:(a,b)=>{for(var c=0;c<a;c++){var d=F.ie.createQueryEXT();if(!d){for(N||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=cb(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Pc:(a,b)=>{db(a,b,"createRenderbuffer",H)},Oc:(a,b)=>{db(a,b,"createTexture",J)},ba:(a,b)=>{db(a,b,"createVertexArray",Za)},Rc:a=>F.generateMipmap(a),Nc:(a,b,c,d,e,g,f)=>oc("getActiveAttrib",a,b,c,d,e,g,f),Mc:(a,b,c,d,e,g,f)=>oc("getActiveUniform",a,b,c,d,e,g,f),Lc:(a,b,c,d)=>{a=F.getAttachedShaders(G[a]);
var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},Kc:pc,Jc:(a,b)=>qc(a,b,4),Ic:(a,b,c)=>{c?u[c>>2]=F.getBufferParameter(a,b):N||=1281},Hc:()=>{var a=F.getError()||N;N=0;return a},Gc:(a,b)=>qc(a,b,2),Fc:(a,b,c,d)=>{a=F.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Ec:(a,b)=>qc(a,b,0),Cc:(a,b,c,d)=>{a=F.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},
Dc:(a,b,c)=>{if(c)if(a>=Wa)N||=1281;else if(a=G[a],35716==b)a=F.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.we){var d=F.getProgramParameter(a,35718);for(b=0;b<d;++b)a.we=Math.max(a.we,F.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.we}else if(35722==b){if(!a.ue)for(d=F.getProgramParameter(a,35721),b=0;b<d;++b)a.ue=Math.max(a.ue,F.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.ue}else if(35381==b){if(!a.ve)for(d=F.getProgramParameter(a,35382),b=0;b<
d;++b)a.ve=Math.max(a.ve,F.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ve}else u[c>>2]=F.getProgramParameter(a,b);else N||=1281},fa:rc,ha:sc,ea:rc,ga:sc,ia:(a,b,c)=>{c?u[c>>2]=F.ie.getQueryEXT(a,b):N||=1281},Ac:(a,b,c)=>{c?u[c>>2]=F.getRenderbufferParameter(a,b):N||=1281},yc:(a,b,c,d)=>{a=F.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?O(a,d,b):0;c&&(u[c>>2]=b)},xc:(a,b,c,d)=>{a=F.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},wc:(a,
b,c,d)=>{if(a=F.getShaderSource(K[a]))b=0<b&&d?O(a,d,b):0,c&&(u[c>>2]=b)},zc:(a,b,c)=>{c?35716==b?(a=F.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=F.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=F.getShaderParameter(K[a],b):N||=1281},vc:a=>{var b=$a[a];if(!b){switch(a){case 7939:b=Q(tc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=F.getParameter(a))||(N||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${F.getParameter(7938)})`);
break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:N||=1280}$a[a]=b}return b},uc:(a,b,c)=>{c?w[c>>2]=F.getTexParameter(a,b):N||=1281},tc:(a,b,c)=>{c?u[c>>2]=F.getTexParameter(a,b):N||=1281},qc:wc,sc:(a,b,c)=>{xc(a,b,c,2)},rc:(a,b,c)=>{xc(a,b,c,0)},nc:(a,b,c)=>{c?u[c>>2]=F.getVertexAttribOffset(a,b):N||=1281},pc:(a,b,c)=>{yc(a,b,c,2)},oc:(a,b,c)=>{yc(a,
b,c,5)},mc:(a,b)=>F.hint(a,b),lc:a=>(a=Xa[a])?F.isBuffer(a):0,kc:a=>F.isEnabled(a),jc:a=>(a=Ya[a])?F.isFramebuffer(a):0,ic:a=>(a=G[a])?F.isProgram(a):0,ma:a=>(a=M[a])?F.ie.isQueryEXT(a):0,hc:a=>(a=H[a])?F.isRenderbuffer(a):0,gc:a=>(a=K[a])?F.isShader(a):0,fc:a=>(a=J[a])?F.isTexture(a):0,aa:a=>(a=Za[a])?F.isVertexArray(a):0,ec:a=>F.lineWidth(a),dc:zc,cc:(a,b)=>{3317==a?ab=b:3314==a&&(bb=b);F.pixelStorei(a,b)},_a:(a,b)=>{F.pf.polygonModeWEBGL(a,b)},bc:(a,b)=>F.polygonOffset(a,b),ab:(a,b,c)=>{F.gf.polygonOffsetClampEXT(a,
b,c)},ja:(a,b)=>{F.ie.queryCounterEXT(M[a],b)},ac:(a,b,c,d,e,g,f)=>{(f=Ac(g,e,c,d,f))?F.readPixels(a,b,c,d,e,g,f):N||=1280},$b:()=>{},_b:(a,b,c,d)=>F.renderbufferStorage(a,b,c,d),Zb:(a,b)=>{F.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>F.scissor(a,b,c,d),Wb:()=>{N||=1280},Vb:Bc,Ub:(a,b,c)=>F.stencilFunc(a,b,c),Tb:(a,b,c,d)=>F.stencilFuncSeparate(a,b,c,d),Sb:a=>F.stencilMask(a),Rb:(a,b)=>F.stencilMaskSeparate(a,b),Qb:(a,b,c)=>F.stencilOp(a,b,c),Pb:(a,b,c,d)=>F.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,
l,n)=>{n=n?Ac(l,f,d,e,n):null;F.texImage2D(a,b,c,d,e,g,f,l,n)},Nb:(a,b,c)=>F.texParameterf(a,b,c),Mb:(a,b,c)=>{F.texParameterf(a,b,w[c>>2])},Lb:(a,b,c)=>F.texParameteri(a,b,c),Kb:(a,b,c)=>{F.texParameteri(a,b,u[c>>2])},Jb:(a,b,c,d,e,g,f,l,n)=>{n=n?Ac(l,f,e,g,n):null;F.texSubImage2D(a,b,c,d,e,g,f,l,n)},Ib:Cc,Hb:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);F.uniform1fv(W(a),d)},Gb:(a,b)=>{F.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(288>=b)for(var d=Dc[b],
e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);F.uniform1iv(W(a),d)},Eb:(a,b,c)=>{F.uniform2f(W(a),b,c)},Cb:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);F.uniform2fv(W(a),d)},Bb:(a,b,c)=>{F.uniform2i(W(a),b,c)},Ab:(a,b,c)=>{if(144>=b){b*=2;for(var d=Dc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);F.uniform2iv(W(a),d)},zb:Ec,yb:(a,b,c)=>{if(96>=b){b*=3;for(var d=
X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);F.uniform3fv(W(a),d)},xb:(a,b,c,d)=>{F.uniform3i(W(a),b,c,d)},wb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Dc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);F.uniform3iv(W(a),d)},vb:(a,b,c,d,e)=>{F.uniform4f(W(a),b,c,d,e)},ub:(a,b,c)=>{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+
1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=w.subarray(c>>2,c+16*b>>2);F.uniform4fv(W(a),d)},tb:(a,b,c,d,e)=>{F.uniform4i(W(a),b,c,d,e)},rb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Dc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);F.uniform4iv(W(a),d)},qb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],g=0;g<b;g+=4)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2]}else e=w.subarray(d>>2,d+
16*b>>2);F.uniformMatrix2fv(W(a),!!c,e)},pb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],g=0;g<b;g+=9)e[g]=w[d+4*g>>2],e[g+1]=w[d+(4*g+4)>>2],e[g+2]=w[d+(4*g+8)>>2],e[g+3]=w[d+(4*g+12)>>2],e[g+4]=w[d+(4*g+16)>>2],e[g+5]=w[d+(4*g+20)>>2],e[g+6]=w[d+(4*g+24)>>2],e[g+7]=w[d+(4*g+28)>>2],e[g+8]=w[d+(4*g+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);F.uniformMatrix3fv(W(a),!!c,e)},ob:Fc,nb:Gc,mb:a=>{F.validateProgram(G[a])},lb:(a,b)=>F.vertexAttrib1f(a,b),kb:(a,b)=>{F.vertexAttrib1f(a,w[b>>2])},jb:(a,b,c)=>F.vertexAttrib2f(a,
b,c),ib:(a,b)=>{F.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},gb:(a,b,c,d)=>F.vertexAttrib3f(a,b,c,d),fb:(a,b)=>{F.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},eb:(a,b,c,d,e)=>F.vertexAttrib4f(a,b,c,d,e),db:(a,b)=>{F.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Qd:(a,b)=>{F.vertexAttribDivisor(a,b)},cb:Hc,bb:Ic,s:()=>0,qa:(a,b,c)=>Jc(a,{He:u[c>>2],ye:u[c+4>>2],hf:u[c+8>>2],df:b,qe:u[c+12>>2],Qe:u[c+16>>2]}),O:(a,b)=>{a=U(a);return a?a.requestPointerLock?Gb()?Yb(a):b?(Eb(Yb,2,[a]),1):-2:-1:
-4},Qa:()=>{ma("OOM")},Oa:a=>{eval(a?A(r,a):"")},T:Kc,y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Lc(a,b),H:(a,b,c,d)=>Mc(a,b,c,d,12,"blur"),o:Pb,q:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},I:(a,b,c,d)=>Mc(a,b,c,d,13,"focus"),A:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Nc(a,b,c,d,"webkitfullscreenchange");return Nc(a,b,c,d,"fullscreenchange")},R:(a,b,c)=>Kc()?-1:Oc(a,b,c,26,"gamepadconnected"),Q:(a,b,c)=>Kc()?-1:Oc(a,
b,c,27,"gamepaddisconnected"),D:(a,b,c,d)=>Pc(a,b,c,d,2,"keydown"),B:(a,b,c,d)=>Pc(a,b,c,d,1,"keypress"),C:(a,b,c,d)=>Pc(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=V(a);xb(a,b,c)},N:(a,b,c,d)=>Rc(a,b,c,d,5,"mousedown"),L:(a,b,c,d)=>Rc(a,b,c,d,33,"mouseenter"),K:(a,b,c,d)=>Rc(a,b,c,d,34,"mouseleave"),v:(a,b,c,d)=>Rc(a,b,c,d,8,"mousemove"),M:(a,b,c,d)=>Rc(a,b,c,d,6,"mouseup"),E:(a,b,c,d)=>document.body?.requestPointerLock?(a=U(a))?Sc(a,b,c,d):-4:-1,w:(a,b,c,d)=>Tc(a,b,c,d),F:(a,b,c,d)=>Uc(a,b,c,d,25,"touchcancel"),
t:(a,b,c,d)=>Uc(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>Uc(a,b,c,d,24,"touchmove"),G:(a,b,c,d)=>Uc(a,b,c,d,22,"touchstart"),z:(a,b,c)=>Vc(a,b,c),J:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?dd(a,b,c,d):-1:-4,ra:a=>document.title=a?A(r,a):"",r:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ua:(a,b)=>{var c=0,d=0,e;for(e of gd()){var g=b+c;v[a+d>>2]=g;c+=O(e,g,Infinity)+1;d+=4}return 0},Va:(a,b)=>{var c=gd();v[a>>2]=c.length;
a=0;for(var d of c)a+=hb(d)+1;v[b>>2]=a;return 0},V:()=>52,Wa:()=>52,Ta:function(){return 70},W:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,B=r[f+n],L=hd[t];0===B||10===B?((1===t?fa:k)(A(L)),L.length=0):L.push(B)}e+=l}v[d>>2]=e;return 0},Z:$b,a:ac,Sa:bc,b:cc,hb:dc,Pa:ec,_:fc,zd:gc,x:hc,l:ic,f:kc,j:lc,d:mc,c:nc,Y:pc,n:wc,ed:zc,$:Bc,i:Cc,g:Ec,h:Fc,Bc:Gc,e:Hc,Db:Ic,sb:function(a,b){a=r.subarray(a,a+b);b="";for(var c=0;c<a.length;c++)b+=String.fromCharCode(a[c]);
a=btoa(b);console.log(a);prompt("Copy this Base64 string and post it as a comment it's your game state:",a)},Yb:function(){var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}};function qd(a=[]){var b=od;a.unshift(ba);var c=a.length,d=Kb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Lb(f);e+=4});v[e>>2]=0;try{var g=b(c,d);Ba(g)}catch(f){za(f)}}
function rd(a=aa){function b(){h.calledRun=!0;if(!p){Z.Vd();h.onRuntimeInitialized?.();h.noInitialRun||qd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.push(c)}sa(ta)}}if(0<y)z=rd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();sa(ua);0<y?z=rd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;ia=Z.Ud;c=ia.buffer;q=new Int8Array(c);ja=new Int16Array(c);r=new Uint8Array(c);ka=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);la=new BigInt64Array(c);new BigUint64Array(c);Tb=Z.Xd;c=Z;h._main=od=c.Wd;P=c.Yd;Nb=c.Zd;Kb=c._d;Mb=c.$d;y--;h.monitorRunDependencies?.(y);0==y&&z&&(c=z,z=null,c());return Z}y++;h.monitorRunDependencies?.(y);var b={a:pd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,
(d,e)=>{c(a(d,e))})});na??=h.locateFile?h.locateFile("game.wasm",da):da+"game.wasm";return a((await qa(b)).instance)})();rd();
